name: ball_game
description: "Ball Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  injectable: ^2.7.1+4
  json_annotation: ^4.9.0
  logger: ^2.6.2
  shared_preferences: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

dev_dependencies:
  build_runner: ^2.10.5
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  freezed: ^3.2.4
  injectable_generator: ^2.12.0
  json_serializable: ^6.11.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
